#!/usr/bin/env ruby

require 'csv'

if ARGV.length != 1
    puts ""
    puts "Error, invalid arguments: "
    puts
    puts "\tUsage: script.rb <filename>"
    puts ""
    exit 1
end


filename = ARGV[0]

providers = CSV.read(filename)

skippedHeader = false

providers.each do |provider|

        if skippedHeader == false
            skippedHeader = true
            next
        end

        puts ""
        puts "# Provider ID: #{provider[0]} #"
        puts "## Provider Name: #{provider[1]} ##"
        puts "Description: #{provider[2]}"
        puts ""
    
        puts "Main Street Address: #{provider[3]}  "
        puts "City: #{provider[4]}  "
        puts "State: #{provider[5]}  "
        puts "Zip Code: #{provider[6]}  "
    
        puts ""
        puts "Main Phone Number: #{provider[7]}  "
        puts "Main Contact Title: #{provider[8]}  "
        puts "Main Contact Email: #{provider[9]}  "
        puts "Website Address: #{provider[10]}  "
        puts "Intake Procedure: #{provider[11]}  "
        puts "Program Fees: #{provider[6]}  "

end

puts "Successfully converted csv to Markdown file: print.md"